server:
  port: 8090

spring:
  redis:
    clientName: redis
    host: 8.129.15.54
    port: 6379
    password:
    database: 1
    timeout: 30000
    jedis:
      pool:
        max-active: 100
        max-wait: 30000
        max-idle: 300
    ssl: false

